services:
  runner:
    image: ghcr.io/marcelkohlmeyer/local-actions-runner:latest
    restart: always
    environment:
      - REPO=${REPO}
      - TOKEN=${TOKEN}
      - TESTCONTAINERS_HOST_OVERRIDE=host.docker.internal
    group_add:
      - "${DOCKER_GID}"   # e.g. DOCKER_GID=$(getent group docker | cut -d: -f3)
    extra_hosts:
      - "host.docker.internal:host-gateway"
    deploy:
      mode: replicated
      replicas: ${REPLICA_COUNT}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
